config/routes.rb
Friendlocatr::Application.routes.draw do
  resources :users do
    collection do
      get :nearest_friends
    end
  end

  root :to => 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_numericality_of :latitude, :longitude
  validates_inclusion_of :latitude, :in => 0..90
  validates_inclusion_of :longitude, :in => 0..180

  validates_presence_of :name, :latitude, :longitude
  validates_length_of :name, :within => 0..50
  validates_uniqueness_of :name
  validates_uniqueness_of :latitude, :scope => :longitude
  validates_uniqueness_of :longitude, :scope => :latitude

  scope :nearest, order(:distance.asc)

  before_save :compute_distance

  private
  def compute_distance
    self.distance = ((self.latitude - self.longitude)**2)**(1/2)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to root_path, notice: 'Successfully added friend!'
    else
      redirect_to root_path, alert: "Error adding friend: invalid coordinates"
    end
  end

  def nearest_friends
    @friends = User.nearest.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Friendlocatr
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    - if notice
      .notice=notice
    - if alert
      .alert=alert
    = yield

app/views/users/index.html.haml
=link_to 'Show nearest friends', nearest_friends_users_path

#add_friend
  =simple_form_for @user do |f|
    =f.input :name
    =f.input :latitude, :label => 'Latitude'
    =f.input :longitude, :label => 'Longitude'
    =f.submit 'Add friend'

-if @users
  #users
    %table{border: 1, cellpadding: 5}
      %thead
        %tr
          %th Name
          %th Latitude
          %th Longitude
      %tbody
        -@users.each do |user|
          %tr
            %td=user.name
            %td=user.latitude
            %td=user.longitude

app/views/users/nearest_friends.html.haml
-if @friends
  %table
    %thead
      %tr
        %th Name
        %th Latitude
        %th Longitude
    %tbody
      -@friends.each do |friend|
        %tr
          %td=friend.name
          %td=friend.latitude
          %td=friend.longitude